/*
 * CophylogenySimulator.java
 *
 * Cophy: Cophylogenetics for BEAST
 *
 * Copyright (C) 2014 Arman Bilge <armanbilge@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package cophy.simulation;

import cophy.model.CophylogenyModel;
import cophy.model.TrajectoryState;
import cophy.simulation.CophylogeneticEvent.CospeciationEvent;
import dr.evolution.tree.*;

import java.util.NavigableMap;
import java.util.TreeMap;

/**
 *
 * @author Arman D. Bilge <armanbilge@gmail.com>
 *
 */
public abstract class CophylogenySimulator<M extends CophylogenyModel> {

    public static final String HOST = "host";
    public static final String EXTINCT = "extinct";

    private final M model;
    private final boolean complete;

    private final NavigableMap<Double,CospeciationEvent> cospeciationEvents;

    private boolean cospeciationsKnown = false;

    public CophylogenySimulator(final M model, final boolean complete) {
        this.model = model;
        this.complete = complete;
        final Tree hostTree = model.getHostTree();
        cospeciationEvents = new TreeMap<Double, CospeciationEvent>();
        if (hostTree instanceof MutableTree) {
            ((MutableTree) hostTree).addMutableTreeListener(new MutableTreeListener() {
                @Override
                public void treeChanged(final Tree hostTree) {
                    cospeciationsKnown = false;
                }
            });
        }
    }

    private void initializeCospeciationEvents() {
        cospeciationEvents.clear();
        final Tree hostTree = model.getHostTree();
        for (int i = 0; i < hostTree.getInternalNodeCount(); ++i) {
            final NodeRef host = hostTree.getInternalNode(i);
            final double height = hostTree.getNodeHeight(host);
            final CospeciationEvent event = new CospeciationEvent(host, hostTree.getChild(host, 0), hostTree.getChild(host, 1), height);
            cospeciationEvents.put(height, event);
            cospeciationsKnown = true;
        }
    }

    public NavigableMap<Double,CospeciationEvent> getCospeciationEvents() {
        if (!cospeciationsKnown)
            initializeCospeciationEvents();
        return cospeciationEvents;
    }

    protected final boolean isComplete() {
        return complete;
    }

    public FlexibleTree createTree() {
        final NodeRef hostRoot = model.getHostTree().getRoot();
        final double originHeight = model.getOriginHeight();
        final FlexibleNode root = new FlexibleNode();
        root.setHeight(originHeight);
        root.setAttribute(HOST, hostRoot);
        return new FlexibleTree(root);
    }

    public Tree simulateTree() {
        return simulateTree(0.0);
    }

    public Tree simulateTree(final double until) {

        final Tree tree = createTree();
        resumeSimulation(tree, until);
        return tree;

    }

    public void resumeSimulation(final Tree tree, final double until) {

        if (!(tree instanceof FlexibleTree))
            throw new RuntimeException("Tree not generated by a"
                    + " CophylogenySimulator.");

        if (!complete)
            throw new RuntimeException("Cannot resume incomplete simulation");

        for (int i = 0; i < tree.getExternalNodeCount(); ++i) {
            final FlexibleNode node = (FlexibleNode) tree.getExternalNode(i);
            if (node.getAttribute(EXTINCT) == null) {
                // Does not have EXTINCT attribute
                simulateSubtree(node,
                                (NodeRef) node.getAttribute(HOST),
                                node.getHeight(),
                                until);
            }
        }

        ((FlexibleTree) tree).adoptTreeModelOrdering();

    }

    protected FlexibleNode simulateSubtree(final NodeRef hostNode,
                                           final double height,
                                           final double until) {

        final FlexibleNode node = new FlexibleNode();
        simulateSubtree(node, hostNode, height, until);
        return node;

    }

    protected abstract FlexibleNode simulateSubtree(final FlexibleNode guestNode,
                                                    final NodeRef hostNode,
                                                    double height,
                                                    final double until);

    public double simulateSpeciationEvent(final Tree tree,
                                          final NodeRef node,
                                          final double height) {

        final Tree hostTree = model.getHostTree();
        final NodeRef hostNode = (NodeRef) tree.getNodeAttribute(node, HOST);

        final double w;
        if (hostTree.getNodeHeight(hostNode) == height) // Cospeciation event
            w = simulateCospeciationEvent(tree, node, height);
        else // Birth event
            w = simulateBirthEvent(tree, node, height);

        ((FlexibleTree) tree).adoptTreeModelOrdering();
        return w;
    }

    protected double
            simulateCospeciationEvent(final Tree tree,
                                      final NodeRef node,
                                      final double height) {

        final MutableTree mutableTree = (MutableTree) tree;

        final NodeRef host = (NodeRef) tree.getNodeAttribute(node, HOST);
        final FlexibleNode left = new FlexibleNode();
        left.setAttribute(HOST, host);
        mutableTree.addChild(node, left);
        final FlexibleNode right = new FlexibleNode();
        right.setAttribute(HOST, right);
        mutableTree.addChild(node, right);

        return 1.0; // Cospeciation events are always guaranteed
                    // i.e. occur with equal weight
}

    protected abstract double
            simulateBirthEvent(final Tree tree,
                               final NodeRef node,
                               final double height);


    public TrajectoryState createTrajectory(final Tree guest) {
        return new TrajectoryState(getModel().getOriginHeight(), guest.getRoot(), getModel().getHostTree().getRoot());
    }

    public void resumeSimulation(final TrajectoryState state, final double until) {

        CospeciationEvent nextCospeciationEvent = nextCospeciationEvent(state.getHeight());
        while (state.getHeight() > Math.max(until, nextCospeciationEvent.getHeight())) {

            final CophylogeneticEvent nextEvent = nextEvent(state);
            final double nextEventHeight = state.getHeight() - nextEvent.getWaitingTime();
            if (nextEventHeight <= until) {
                state.setHeight(until);
                break;
            } else if (nextEventHeight <= nextCospeciationEvent.getHeight()) {
                nextCospeciationEvent.apply(state);
                nextCospeciationEvent = nextCospeciationEvent(state.getHeight());
            } else {
                nextEvent.apply(state);
            }

        }

    }

    protected abstract CophylogeneticEvent nextEvent(final TrajectoryState state);

    protected CospeciationEvent nextCospeciationEvent(final double height) {
        return cospeciationEvents.lowerEntry(height).getValue();
    }


    public double
            simulateSpeciationEvent(final TrajectoryState state,
                                    final double height,
                                    final NodeRef guest,
                                    final NodeRef host) {

        final Tree hostTree = model.getHostTree();
        if (hostTree.getNodeHeight(host) == height) // Cospeciation event
            return simulateCospeciationEvent(state, height);
        else // Birth event
            return simulateBirthEvent(state, height, guest, host);

    }

    protected double
            simulateCospeciationEvent(final TrajectoryState state,
                                      final double height) {

        return getCospeciationEvents().get(height).apply(state);
    }

    protected abstract double
            simulateBirthEvent(TrajectoryState state,
                               double height,
                               NodeRef guest,
                               NodeRef host);

    public M getModel() {
        return model;
    }

}
